# Generated by Django 4.1.6 on 2025-08-28 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_model_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_owners', models.IntegerField(default=None)),
                ('registration_number', models.CharField(default=None, max_length=8, unique=True)),
                ('manufacture_year', models.IntegerField(default=None)),
                ('number_of_doors', models.IntegerField(default=5)),
                ('mileage', models.IntegerField(default=None)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_model_app.carmodel')),
            ],
            options={
                'ordering': ('car_id',),
            },
        ),
    ]
