# Generated by Django 4.1.6 on 2025-08-28 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advertisement_id', models.AutoField(primary_key=True, serialize=False)),
                ('advertisement_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.car')),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.appuser')),
            ],
            options={
                'ordering': ('advertisement_id',),
            },
        ),
    ]
