# Generated by Django 4.1.6 on 2025-08-28 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_name', models.CharField(default=None, max_length=255)),
                ('street_number', models.CharField(default=None, max_length=255)),
                ('zip_code', models.CharField(default=None, max_length=5)),
                ('city', models.CharField(default=None, max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.appuser')),
            ],
            options={
                'ordering': ('profile_id',),
            },
        ),
    ]
