# Generated by Django 4.1.6 on 2025-08-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('car_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(default=None, max_length=50)),
                ('model', models.CharField(default=None, max_length=50, unique=True)),
            ],
            options={
                'ordering': ('car_model_id',),
            },
        ),
    ]
