# Generated by Django 4.1.6 on 2025-08-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(default=None, max_length=155, unique=True)),
                ('password', models.CharField(default=None, max_length=255)),
            ],
            options={
                'ordering': ('account_id',),
            },
        ),
    ]
